"""init schema

Revision ID: 0b7f59ed1b7e
Revises: 
Create Date: 2025-08-12 01:33:27.896379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7f59ed1b7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('idx_creation', 'companies', ['created_at'], unique=False)
    op.create_table('projects',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ID_company', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ID_company'], ['companies.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('users',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ID_company', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ID_company'], ['companies.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('idx_company_creation', 'users', ['ID_company', 'created_at'], unique=False)
    op.create_table('projects_memberships',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ID_company', sa.Integer(), nullable=False),
    sa.Column('ID_user', sa.Integer(), nullable=False),
    sa.Column('ID_project', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ID_company'], ['companies.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ID_project'], ['projects.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ID_user'], ['users.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('idx_company_user_project_creation', 'projects_memberships', ['ID_company', 'ID_user', 'ID_project', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_company_user_project_creation', table_name='projects_memberships')
    op.drop_table('projects_memberships')
    op.drop_index('idx_company_creation', table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_index('idx_creation', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
